/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 deskroom_no_merge.glb 
*/

import React, { useRef } from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/deskroom_no_merge.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[3.02, 2.098, -3.339]} rotation={[0, 0.445, 0.098]}>
        <mesh
          geometry={nodes.Plane004.geometry}
          material={materials["feuilles.001"]}
        />
        <mesh
          geometry={nodes.Plane004_1.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          geometry={nodes.Plane004_2.geometry}
          material={materials["wood chaise.001"]}
        />
        <mesh
          geometry={nodes.Plane004_3.geometry}
          material={materials["Cactus 1.001"]}
        />
      </group>
      <group position={[0.548, 1.365, -2.858]}>
        <mesh
          geometry={nodes.Cube123.geometry}
          material={materials["Material.014"]}
        />
        <mesh geometry={nodes.Cube123_1.geometry} material={materials.Grey} />
      </group>
      <group position={[-3.401, 1.968, -3.204]}>
        <mesh
          geometry={nodes.Cube143.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Cube143_1.geometry}
          material={materials["Book Cover Orange.001"]}
        />
        <mesh
          geometry={nodes.Cube143_2.geometry}
          material={materials["Black plastic"]}
        />
      </group>
      <group position={[-2.124, 0.895, 0.349]} rotation={[-0.275, 1.133, 0.25]}>
        <mesh
          geometry={nodes.Cube009.geometry}
          material={materials["wood chaise"]}
        />
        <mesh
          geometry={nodes.Cube009_1.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <mesh
        geometry={nodes.Etagère.geometry}
        material={materials["wood meuble"]}
        position={[-3.635, -0.397, 2.854]}
      />
      <mesh
        geometry={nodes.Coffee_Cup.geometry}
        material={materials["Material.012"]}
        position={[1.262, 1.422, -2.955]}
        rotation={[0, 0.57, 0]}
      />
      <group position={[0.064, 1.353, -2.858]}>
        <mesh
          geometry={nodes.Cube005.geometry}
          material={materials["Material.007"]}
        />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.Grey} />
      </group>
      <group position={[0.088, 0.887, -1.462]} rotation={[0, 1.124, 0]}>
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials["Black plastic"]}
        />
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Plane001_2.geometry}
          material={materials["Book Cover Red.001"]}
        />
      </group>
      <group position={[1.738, 1.492, -3.577]}>
        <mesh
          geometry={nodes.Cube126.geometry}
          material={materials["Darker wood"]}
        />
        <mesh
          geometry={nodes.Cube126_1.geometry}
          material={materials["Cactus 3"]}
        />
      </group>
      <group position={[1.335, 1.511, -3.681]}>
        <mesh
          geometry={nodes.Cube127.geometry}
          material={materials["Darker wood"]}
        />
        <mesh
          geometry={nodes.Cube127_1.geometry}
          material={materials["Cactus 2"]}
        />
      </group>
      <group position={[-3.426, 0.782, -2.612]}>
        <mesh
          geometry={nodes.Cube130.geometry}
          material={materials["wood meuble"]}
        />
        <mesh geometry={nodes.Cube130_1.geometry} material={materials.Grey} />
      </group>
      <mesh
        geometry={nodes.Bureau.geometry}
        material={materials["Material.002"]}
        position={[0.21, 1.286, -3.122]}
      />
      <mesh
        geometry={nodes.Stores.geometry}
        material={materials["Lighter wood"]}
        position={[-3.862, 4.097, -0.002]}
        rotation={[0, 0, -0.376]}
      />
      <group
        position={[-3.549, 2.679, 2.547]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      >
        <mesh
          geometry={nodes.Cube023.geometry}
          material={materials["Book Cover Red.002"]}
        />
        <mesh
          geometry={nodes.Cube023_1.geometry}
          material={materials["Book Cover Orange.002"]}
        />
        <mesh
          geometry={nodes.Cube023_2.geometry}
          material={materials["Book Cover Pink.001"]}
        />
      </group>
      <group position={[-0.982, 1.768, -3.499]}>
        <mesh
          geometry={nodes.Cylinder020.geometry}
          material={materials.Lampe}
        />
        <mesh
          geometry={nodes.Cylinder020_1.geometry}
          material={materials.Letton}
        />
        <mesh
          geometry={nodes.Cylinder020_2.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Cylinder020_3.geometry}
          material={materials["Black plastic.004"]}
        />
        <mesh
          geometry={nodes.Cylinder020_4.geometry}
          material={materials["wood meuble.001"]}
        />
      </group>
      <group position={[-3.604, 1.734, 3.103]} rotation={[0, -1.368, 0]}>
        <mesh
          geometry={nodes.Cube004.geometry}
          material={materials["red.001"]}
        />
        <mesh
          geometry={nodes.Cube004_1.geometry}
          material={materials["Material.017"]}
        />
        <mesh
          geometry={nodes.Cube004_2.geometry}
          material={materials["Material.018"]}
        />
        <mesh
          geometry={nodes.Cube004_3.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          geometry={nodes.Cube004_4.geometry}
          material={materials["Material.020"]}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials["Lighter wood.002"]}
        position={[-3.852, 3.027, 1.259]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials["Lighter wood.001"]}
        position={[-3.852, 3.027, -1.295]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["wood meuble"]}
        position={[-3.863, 4.328, -0.012]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.Material}
        position={[0.21, -0.001, 0.457]}
      />
      <group position={[-0.379, 1.57, -3.862]}>
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials["Black plastic"]}
        />
        <mesh
          geometry={nodes.Cylinder_1.geometry}
          material={materials["Black plastic.002"]}
        />
      </group>
      <group
        position={[-3.579, 2.634, 3.227]}
        rotation={[-Math.PI, 0.686, -Math.PI]}
      >
        <mesh
          geometry={nodes.bool_obj_data002.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.bool_obj_data002_1.geometry}
          material={materials["Material.016"]}
        />
      </group>
      <group position={[-3.522, 1.85, 2.473]} rotation={[0, -0.325, 0]}>
        <mesh
          geometry={nodes.bool_obj_data003.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.bool_obj_data003_1.geometry}
          material={materials["Material.016"]}
        />
      </group>
      <group position={[-3.332, 1.589, -3.49]} rotation={[0, 0.001, 0]}>
        <mesh
          geometry={nodes.bool_obj_data001.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.bool_obj_data001_1.geometry}
          material={materials["Material.016"]}
        />
      </group>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials["Material.009"]}
        position={[-0.215, 3.007, -3.931]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Material.010"]}
      />
      <mesh
        geometry={nodes.Plane003_1.geometry}
        material={materials["Material.011"]}
      />
      <mesh
        geometry={nodes.Plane003_2.geometry}
        material={materials["WoodenFlooring 6"]}
      />
    </group>
  );
}

useGLTF.preload("/deskroom_no_merge.glb");
